### PR TITLE
Fix the profile picture

### LINKED ISSUE #397: Modify the profile picture, to see something, not just a black screen

### PR DESCRIPTION
**Pull request by mbouaissi**
This PR fix the fact that before, we no background or no profile picture at all. Now we have the letter of the user, as well as a colorfull background. It add this in the profile screen, as well as the beacon screen

Closes #397

### CODE REVIEW

File: app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModel.kt [hunk 1]
```diff
@@ -163,6 +163,7 @@ constructor(
     viewModelScope.launch {
       repository.getItem(id).collect { fetchedProfile ->
         fetchedProfile.onSuccess { profile ->
+          profile.profilePictureUri = null // TODO : @Clarence, pls can you do it more properly
```
Comment (KlaKalma) [inline app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModel.kt:166]: As decided on discord, with regards to the PRD, and the "future improvements" we can do, I don't think we should remove this. Just leave it as null.

**Review by KlaKalma — COMMENTED** [review]
We just change the uri and it should be fine !

**Review by KlaKalma — APPROVED** [review]
lgtm

File: app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/profile/ImagesActions.kt [hunk 2]
```diff
@@ -3,25 +3,47 @@ package ch.epfl.cs311.wanderwave.ui.components.profile
...
+import ch.epfl.cs311.wanderwave.ui.theme.ProfileBackground2
+import ch.epfl.cs311.wanderwave.ui.theme.ProfileBackground20
+import ch.epfl.cs311.wanderwave.ui.theme.ProfileBackground21
+import ch.epfl.cs311.wanderwave.ui.theme.ProfileBackground3
+import ch.epfl.cs311.wanderwave.ui.theme.ProfileBackground4
+import ch.epfl.cs311.wanderwave.ui.theme.ProfileBackground5
+import ch.epfl.cs311.wanderwave.ui.theme.ProfileBackground6
+import ch.epfl.cs311.wanderwave.ui.theme.ProfileBackground7
+import ch.epfl.cs311.wanderwave.ui.theme.ProfileBackground8
+import ch.epfl.cs311.wanderwave.ui.theme.ProfileBackground9
```
Comment (IB-12) [inline app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/profile/ImagesActions.kt:45]: I'm nitpicking, but it would be a little bit cleaner to have a way to generate colors than just a list of themes like that

File: app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/profile/ImagesActions.kt [hunk 3]
```diff
@@ -34,15 +56,17 @@ import coil.compose.AsyncImage
...
-  } else {
-    Image(
-        painter = painterResource(id = R.drawable.profile_picture),
-        contentDescription = "Default profile picture",
-        modifier = modifier)
-  }
+fun SelectImage(modifier: Modifier, imageUri: Uri?, profile: Profile) {
+  // if (imageUri != null) {
+  // AsyncImage(model = imageUri, contentDescription = "Profile picture", modifier = modifier)
+  // } else {
```
Comment (IB-12) [inline app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/profile/ImagesActions.kt:62]: Commented code

File: app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/profile/ImagesActions.kt [hunk 4]
```diff
@@ -34,15 +56,17 @@ import coil.compose.AsyncImage
...
+  PlaceholderProfilePicture(
+      name = profile.firstName,
+      modifier =
+          modifier
+              .size(48.dp) // Ensure the placeholder is circular
+              .background(MaterialTheme.colorScheme.primary, CircleShape))
+  // }
```
Comment (IB-12) [inline app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/profile/ImagesActions.kt:69]: Commented code

**Review by IB-12 — APPROVED** [review]
Well done, looks really good. Besides the couple of comments I left, I think it would be better to increase the size of the letter in the profile pic, lmk what you think
